<?php

declare(strict_types=1);

require __DIR__ . '/bootstrap.php';

use Parallax\Rozmova\PreferenceList;
use Parallax\Rozmova\Romanizer;
use Parallax\Rozmova\UkrainianTransliterator;

$prefs     = PreferenceList::fromJsonFile(__DIR__ . '/../data/preferences.uk.json');
$romanizer = Romanizer::ukrainian(UkrainianTransliterator::NATIONAL, $prefs);

$cases = [
    // The case that started this: standard says Zelenskyi, usage says Zelenskyy.
    'Зеленський'   => 'Zelenskyy',
    'Зеленського'  => 'Zelenskyy',
    'Зеленському'  => 'Zelenskyy',
    'Зеленським'   => 'Zelenskyy',
    'ЗЕЛЕНСЬКИЙ'   => 'ZELENSKYY',

    // Feminine surname is a different person, not a case of the masculine.
    'Зеленська'    => 'Zelenska',
    'Зеленської'   => 'Zelenska',
    'Зеленською'   => 'Zelenska',

    // Declined place names collapse to one invariant English form.
    'Київ'         => 'Kyiv',
    'Києва'        => 'Kyiv',
    'Києві'        => 'Kyiv',
    'Харкові'      => 'Kharkiv',
    'Львова'       => 'Lviv',

    // Translated rather than romanized.
    'Крим'         => 'Crimea',
    'Криму'        => 'Crimea',

    // Multi-word entries, longest match first.
    'Слава Україні' => 'Slava Ukraini',
    'Верховна Рада' => 'Verkhovna Rada',

    // Acronyms.
    'ЗСУ'          => 'ZSU',
    'СБУ'          => 'SBU',

    // Not in the list: falls through to KMU 2010 untouched.
    'Ярошенко'     => 'Yaroshenko',
    'Розмова'      => 'Rozmova',

    // Mixed sentence: overrides and fallthrough in one pass, punctuation intact.
    'Зеленський прибув до Києва.'      => 'Zelenskyy prybuv do Kyiv.',
    'Слава Україні! Героям слава!'     => 'Slava Ukraini! Heroiam slava!',
    'Бої тривають за Бахмут і Авдіївку.' => 'Boi tryvaiut za Bakhmut i Avdiivka.',
];

$pass = $fail = 0;
$failures = [];

foreach ($cases as $in => $want) {
    $got = $romanizer->romanize($in);
    if ($got === $want) {
        $pass++;
    } else {
        $fail++;
        $failures[] = sprintf('  %-34s expected %-24s got %s', $in, $want, $got);
    }
}

// The archive has to be able to show its working.
// A form claimed twice with different answers is an editorial contradiction.
$conflicts = 0;
$allowed   = 0;

try {
    new PreferenceList([
        ['forms' => ['Київ'], 'latin' => 'Kyiv'],
        ['forms' => ['Київ'], 'latin' => 'Kiev'],
    ]);
} catch (InvalidArgumentException $e) {
    $conflicts += str_contains($e->getMessage(), 'Preference conflict') ? 1 : 0;
}

// Collisions generated by declension expansion are caught the same way.
try {
    new PreferenceList([
        ['forms' => ['Зеленський'], 'declension' => 'adj', 'latin' => 'Zelenskyy'],
        ['forms' => ['Зеленського'], 'latin' => 'Zelenskyi'],
    ]);
} catch (InvalidArgumentException $e) {
    $conflicts += str_contains($e->getMessage(), 'Preference conflict') ? 1 : 0;
}

// Declaring the same form twice with the same answer is harmless.
try {
    new PreferenceList([
        ['forms' => ['Київ'], 'latin' => 'Kyiv'],
        ['forms' => ['Київ', 'Києва'], 'latin' => 'Kyiv'],
    ]);
    $allowed = 1;
} catch (InvalidArgumentException) {
    $allowed = 0;
}

$pass += $conflicts + $allowed;
$fail += (2 - $conflicts) + (1 - $allowed);

if ($conflicts < 2) {
    $failures[] = '  conflicting preference entries are not rejected';
}
if ($allowed !== 1) {
    $failures[] = '  identical re-declaration is wrongly rejected';
}

echo "preference layer\n", str_repeat('-', 70), "\n";
printf("  %d passed, %d failed  (%d surface forms indexed)\n", $pass, $fail, $prefs->count());
if ($failures) {
    echo "\n", implode("\n", $failures), "\n";
}

echo "\naudit trail\n", str_repeat('-', 70), "\n";
$sentence = 'Зеленський подякував ЗСУ за оборону Бахмута.';
echo "  source   $sentence\n";
echo "  output   ", $romanizer->romanize($sentence), "\n";
foreach ($romanizer->appliedOverrides() as $o) {
    printf("  applied  %-14s -> %-12s %s\n", $o['cyrillic'], $o['latin'], $o['gloss'] ? "({$o['gloss']})" : '');
}

exit($fail === 0 ? 0 : 1);
